on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-20.04
    name: deploy
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ./node_modules
      - name: Generate build
        run: npm run build
      - name: Run git-ftp script
        shell: bash
        run: /bin/chmod +x ./.github/workflows/deploy-script.sh && sudo /bin/bash ./.github/workflows/deploy-script.sh
        env:
          DEPLOY_USERNAME: ${{ secrets.username }}
          DEPLOY_SERVER: ${{ secrets.server }}
          DEPLOY_PORT: ${{ secrets.port }}
          DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.ssh_private_key }}
          DEPLOY_LOCAL_PATH: ${{ secrets.local_path }}
          DEPLOY_REMOTE_PATH: ${{ secrets.remote_path }}
